spring.application.name=currencyConverter
server.port=8080



# Disable Spring Boot's default DataSource auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

